networks:
  xrates-net:
    driver: bridge

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0  #supports KRaft
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # node is both broker and controller
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      #broker listens on 9092 -for data. controller mechanism listens on 9093 -the brain of the cluster
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      #voters in the cluster, only 1 here
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      #cluster ID
      CLUSTER_ID: '${CLUSTER_ID}'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - xrates-net
       
  kafka-producer:
    build:
        context: ./kafka-producer
    image: kafka-producer
    container_name: kafka-producer
    init: true #clean any orphan processes in container
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_SERVER: "kafka:9092"
    networks:
      - xrates-net
    
  flink-jobmanager:
    build:
      context: ./flink-processor
    image: flink-processor
    container_name: flink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
        FLINK_PROPERTIES: |
          jobmanager.rpc.address: flink-jobmanager
    networks:
      - xrates-net

  flink-taskmanager:
    build:
      context: ./flink-processor
    image: flink-processor
    container_name: flink-taskmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager
    environment:
        FLINK_PROPERTIES: |
          jobmanager.rpc.address: flink-jobmanager
    networks:
      - xrates-net

  flink-processor:
    build:
        context: ./flink-processor
    image: flink-processor
    container_name: flink-processor
    init: true
    depends_on:
      kafka:
        condition: service_healthy
      kafka-producer:
        condition: service_started
    env_file:
      - .env
    environment:
      KAFKA_SERVER: "kafka:9092"
      POSTGRES_HOST: postgresdb
      POSTGRES_PORT: "5432"
      PYTHONUNBUFFERED: 1
    networks:
      - xrates-net

  postgresdb:
    build:
      context: ./database
    image: postgresimage
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=fx_rates
        #set linux os environment variable inside the container
        - TZ=Africa/Nairobi
        #set the postgreSQL client timezone environment variable
        - PGTZ=Africa/Nairobi
    logging:
        options:
            max-size: 10m
            max-file: "3"
    ports:
    - 5433:5432
    networks:
      - xrates-net
    #force postgres engine to start with Africa/Nairobi timezone settings
    command: postgres -c timezone=Africa/Nairobi